FROM plugins/base:linux-arm

LABEL maintainer="Covergates <covergates@gmail.com>" \
  org.label-schema.name="Drone Covergates Plugin" \
  org.label-schema.vendor="covergates" \
  org.label-schema.schema-version="1.0"

COPY release/linux/arm/drone-covergates /bin/

ENTRYPOINT ["/bin/drone-covergates"]
