FROM plugins/base:windows-amd64

LABEL maintainer="Covergates <covergates@gmail.com>" \
  org.label-schema.name="Drone Covergates Plugin" \
  org.label-schema.vendor="covergates" \
  org.label-schema.schema-version="1.0"

COPY release/windos/amd64/drone-covergates /drone-covergates.exe

ENTRYPOINT [ "\\drone-covergates.exe" ]
